-- Migration script to add store_contents table
-- Run this script in the Supabase SQL Editor

-- Create store_contents table
CREATE TABLE IF NOT EXISTS store_contents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_code VARCHAR(255) NOT NULL,
  content_type VARCHAR(10) NOT NULL CHECK (content_type IN ('text', 'image')),
  display_order INTEGER NOT NULL,
  text_content TEXT,
  image_path TEXT,
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (store_code) REFERENCES stores(store_code) ON DELETE CASCADE
);

-- Add RLS policies for store_contents
ALTER TABLE store_contents ENABLE ROW LEVEL SECURITY;

-- Allow anyone to read all store contents (no authentication required)
CREATE POLICY "Allow public read access for store contents" 
  ON store_contents FOR SELECT 
  USING (true);

-- Allow authenticated users to insert store contents
CREATE POLICY "Allow authenticated users to insert store contents" 
  ON store_contents FOR INSERT 
  WITH CHECK (auth.role() = 'authenticated');

-- Allow authenticated users to update store contents
CREATE POLICY "Allow authenticated users to update store contents" 
  ON store_contents FOR UPDATE 
  USING (auth.role() = 'authenticated');

-- Allow authenticated users to delete store contents
CREATE POLICY "Allow authenticated users to delete store contents" 
  ON store_contents FOR DELETE 
  USING (auth.role() = 'authenticated');

-- Optional: Migrate existing store images to the new content system
-- This will add existing images as content items
-- Uncomment and run this after creating the table if you want to migrate existing data
/*
INSERT INTO store_contents (store_code, content_type, display_order, image_path, image_url)
SELECT 
  store_code, 
  'image' as content_type,
  ROW_NUMBER() OVER (PARTITION BY store_code ORDER BY created_at) as display_order,
  image_path,
  image_url
FROM store_images;
*/ 